platform :android do
    desc "Deploy with Fastlane"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :upload_to_firebase do
        firebase_app_distribution(
            app: "1:771886012881:android:6264e0f5c22015ca1ca8f0",
            testers: "weslleyduarteportifolio@gmail.com",
            groups: "minasbrasil",
            release_notes: sh("git log -1 --pretty='%s'"),
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
        )
    end
    lane :upload_to_store do
        upload_to_play_store(track: 'alpha',apk:'../build/app/outputs/flutter-apk/app-release.apk')
    end
end